### Solicitud para obtener la API
GET https://api-rest-vo9r.onrender.com/api HTTP/1.1

### Solicitud para obtener todos los usuarios
GET https://api-rest-vo9r.onrender.com/api/usuarios HTTP/1.1

### Solicitud para iniciar sesión
POST https://api-rest-vo9r.onrender.com/api/login
Content-Type: application/json

{
    "correo": "juan.perez@example.com",
    "contraseña": "contraseña123"
}

### Solicitud para crear un nuevo usuario
POST https://api-rest-vo9r.onrender.com/api/newUser
Content-Type: application/json

{
        "id": 3,
        "genero": "Femenino",
        "nombre": "jess",
        "apellido": "villa",
        "correo": "kicerey838@hraifi.com",
        "telefono": "9876543210",
        "direccion": "Avenida Siempre Viva 456",
        "fecha_nacimiento": "1995-05-15",
        "contraseña": "123123"
        
}

### Solicitud para crear un nuevo usuario conductor
POST https://api-rest-vo9r.onrender.com/api/newConductor
Content-Type: application/json

{
    "id_conductor": 3,
    "numero_licencia": "ABC123456",
    "fecha_vencimiento": "2025-12-31"
}

### Solicitud para crear un nuevo vehiculo
POST https://api-rest-vo9r.onrender.com/api/newVehiculo
Content-Type: application/json

{
    "id_placa": 3,
    "id_conductor": 3,
    "marca": "Toyota",
    "modelo": "Corolla",
    "ano": "2020",
    "color": "Rojo",
    "capacidad_pasajeros": "5"
}
### Solicitud restaurar contraseña
POST https://api-rest-vo9r.onrender.com/api/sendVerificationCode
Content-Type: application/json

{
    "correo": "juan.perez@example.com"
}

### Solicitud para obtener todos los conductores
GET https://api-rest-vo9r.onrender.com/api/conductores HTTP/1.1

### Solicitud para obtener todos los vehiculos
GET https://api-rest-vo9r.onrender.com/api/vehiculos HTTP/1.1




        

