### Solicitud para obtener la API
GET https://api-rest-vo9r.onrender.com/api HTTP/1.1

### Solicitud para obtener todos los usuarios
GET https://api-rest-vo9r.onrender.com/api/usuarios HTTP/1.1

### Solicitud para iniciar sesión
POST https://api-rest-vo9r.onrender.com/api/login
Content-Type: application/json

{
    "correo": "juan.perez@example.com",
    "contraseña": "contraseña123"
}

### Solicitud para crear un nuevo usuario
POST https://api-rest-vo9r.onrender.com/api/newUser
Content-Type: application/json

{
        "id": 3,
        "genero": "Femenino",
        "nombre": "Ana",
        "apellido": "Gómez",
        "correo": "ana.gomez@example.com",
        "telefono": "9876543210",
        "direccion": "Avenida Siempre Viva 456",
        "fecha_nacimiento": "1995-05-15T00:00:00.000Z",
        "contraseña": "123123",
        "codigo_verificacion": null
}
